# Generated by Django 5.2.7 on 2025-12-02 13:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название соревнования')),
                ('description', models.TextField(verbose_name='Описание')),
                ('sport_type', models.CharField(choices=[('football', 'Футбол'), ('basketball', 'Баскетбол'), ('volleyball', 'Волейбол'), ('tennis', 'Теннис'), ('swimming', 'Плавание'), ('athletics', 'Легкая атлетика'), ('chess', 'Шахматы')], max_length=50, verbose_name='Вид спорта')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('max_participants', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Максимальное количество участников')),
                ('current_participants', models.IntegerField(default=0, verbose_name='Текущее количество участников')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('ongoing', 'В процессе'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='planned', max_length=20, verbose_name='Статус')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичное соревнование')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок регистрации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_competitions', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
                'ordering': ['-start_date'],
                'permissions': [('can_view_all', 'Может просматривать все соревнования'), ('can_edit_competition', 'Может редактировать соревнование'), ('can_delete_competition', 'Может удалять соревнование'), ('can_create_competition', 'Может создавать соревнование'), ('can_register_participant', 'Может регистрировать участников')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'unique_together': {('competition', 'user')},
            },
        ),
    ]
